componente svg
janis-commerce/ui-native pull request #12
Opened 2023-07-25 18:02 UTC by WilliamSaya-lvl30

LINK DE TICKET:
https://janiscommerce.atlassian.net/browse/JUIP-100

DESCRIPCIÓN DEL REQUERIMIENTO:

Contexto
Para cumplir con el objetivo nuestro de poder hacer un release del package ui y comenzar a usarlo en las apps, necesitamos tener un componente para indicarle al usuario que algo está cargando en la app. Para ello, primero necesitamos contar con el componente ‘Svg’.

DESCRIPCIÓN DE LA SOLUCIÓN:

Se Utilizo paquete react-native-svg y react-native-svg-transformer  para renderizar los svgs.

pasar todos los svgs usandos en las apps para tenerlos disponibles en este package

Se creo un componente que tendrá un objeto con todos los svgs disponibles y retornara el solicitado por el usuario.  

Retornar el componente svg wrappeado en un view, para ambos se  destructura props

Se realizaron ajustes necesarios para que storybook los renderizara correctamente.

CÓMO SE PUEDE PROBAR?
Clonar e instalar el Repo de UI-Native

Correr los siguientes 3 comandos en tres pestañas diferentes de la termina

npm run start
npm run android
npm run storybook

Se debe abrir la app en el emulador con storybooks y el navegador en la url http://localhost:7007/ donde se podrá probar
el comportamiento del componente

Para linkear el componente con un proyecto, seguir la siguiente documentación
https://fizzmod.atlassian.net/wiki/spaces/JAPP/pages/2341765125/C+mo+trabajo+con+el+package+UI

2023-07-26 15:36 UTC, GonzaFran commented
@WilliamSaya-lvl30 este PR no tiene los últimos cambios que agregó Nico de storybooks no?

2023-07-26 19:14 UTC, GonzaFran requested changes
@WilliamSaya-lvl30 probé usar el componente vinculandolo con la app de WMS para corroborar que funcione y me crashea la app. El problema es que, aunque esté vinculando el package usando yalc, la carpeta que contiene los svgs no se vincula al repositorio de la misma manera que lo hacen los componentes. Si querés proba vincular el package a la app de picking y corroborar lo que está pasando. Supongo que falta hacer un ajuste para que los svgs sean parte de la instalación del package. Te dejo la captura del error en cuestión:

![Captura desde 2023-07-26 16-11-18](https://github.com/janis-commerce/ui-native/assets/75044106/13c4fc2a-4a99-4b30-b993-d16d2a6dc423)

2023-07-31 18:48 UTC, dam788 approved these changes

2023-07-31 21:17 UTC, GonzaFran approved these changes

2023-08-03 15:47 UTC, pablodamianberdun requested changes
Las interfaces del svg, deben estar dentro del componte.
En ts/interfaces, vamos a declarar types/intefaces que vamos a usar en todo el repo

2023-08-03 15:47 UTC, pablodamianberdun commented on src/ts/interfaces/svgs.ts
> +}
@WilliamSaya-lvl30 esta interface solo se va a utilzar en el componente SVG.
Podemos declararla directamente ahi, dentro del componente.

en ts/interfaces vamos a declarar types e interfaces genericas que podemos utilizar en todo el repo.

2023-08-04 16:42 UTC, pablodamianberdun approved these changes

2023-08-04 16:43 UTC, merged