JUIP-111-crear-readme-ui-native
janis-commerce/ui-native pull request #16
Opened 2023-07-31 23:14 UTC by dam788

**LINK DE TICKET:**
[https://janiscommerce.atlassian.net/browse/JUIP-99](https://janiscommerce.atlassian.net/browse/JUIP-99)

**DESCRIPCIÓN DEL REQUERIMIENTO:** 

**CONTEXTO**
Queres tener publicado la primera version del pkg pero hoy no contamos con info de como se usaria al momento de instalar la libreria en un repo

**NECESIDAD**
Tener un documento que explique como se instala y se usa

**DESCRIPCIÓN DE LA SOLUCIÓN:** 

- Se agregó como instalar
- Se agregó cada componente con sus props, ejemplos de usos y vista previa de como quedaría...

**CRITERIOS DE ACEPTACIÓN:** 
El readme debe contar con:
1. Nombre del pkg
2. Descripcion de como se instala
3. Un ejemplo de algun componente de como se usa

2023-08-01 15:08 UTC, GonzaFran requested changes

2023-08-01 15:08 UTC, GonzaFran commented on README.md
> +source | - | si | string | -
@dam788 acá hay que corregir que la prop source es un objeto y no un string. En observaciones se podría agregar que si no es recibida la prop no renderizará nada o estaría de más? pregunto porque en los otros casos lo que se hizo fue explicar qué es lo que se utiliza cuando no se recibe la prop esperada. Como que, por ejemplo, en avatar, si no le pasas un valor definido usa el valor por defecto.

2023-08-01 15:52 UTC, dam788 commented on README.md
> +source | - | si | string | -
dale ya lo corrijo

2023-08-01 18:43 UTC, GonzaFran approved these changes

2023-08-02 19:08 UTC, Maukr commented on README.md
> +The minimum required versions for using the package are react: x.x.x and react-native: x.x.x.
@dam788 puede ser que esta linea quedó repetida? arriba está con las versiones.

2023-08-02 20:20 UTC, Maukr requested changes
@dam788 la linea 19 parece estar repetida

2023-08-02 20:43 UTC, Maukr approved these changes

2023-08-08 13:40 UTC, christian97dd requested changes
se deja un comentario

2023-08-10 13:40 UTC, merged