Component loading full screen
janis-commerce/ui-native pull request #17
Opened 2023-08-11 12:51 UTC by WilliamSaya-lvl30

LINK DE TICKET:
https://janiscommerce.atlassian.net/browse/JUIP-102

DESCRIPCIÓN DEL REQUERIMIENTO:

Contexto
Actualmente, nuestro MVP para poder lanzar la primera versión de la librería UI native, es contar con el componente LoadingFullScreen y pueda causar un impacto visual en las apps. 

Necesidad
Para ello, en este desarrollo se tendrá que crear dicho componente, utilizando también los componentes de Svg y Loading

As

Desarrollador
I want

Contar con el componente LoadingFullScreen
That

Me sirva para mostrar un loading custom en todas las apps y mejorar el que actualmente tenemos
Acceptance criteria

Deberá aceptar un texto para renderizar

Tendrá que usar el componente Svg y Loading

El wrapper tiene que ser un modal con la prop transparent en true

DESCRIPCIÓN DE LA SOLUCIÓN:

Crear un modal que ocupe toda la pantalla y utilice el componente svg y loader.

No se pudo agregar el efecto blur asi que par una version preliminar se deja un fondo opaco.

CÓMO SE PUEDE PROBAR?
Clonar e instalar el Repo de UI-Native

Correr los siguientes 3 comandos en tres pestañas diferentes de la termina

npm run start
npm run android
npm run storybook

Se debe abrir la app en el emulador con storybooks y el navegador en la url http://localhost:7007/ donde se podrá probar
el comportamiento del componente

Para linkear el componente con un proyecto, seguir la siguiente documentación
https://fizzmod.atlassian.net/wiki/spaces/JAPP/pages/2341765125/C+mo+trabajo+con+el+package+UI

2023-08-14 14:57 UTC, GonzaFran requested changes

2023-08-14 14:57 UTC, GonzaFran commented on storybook/stories/LoadingFullScreen/LoadingFullScreen.stories.js
> +			<LoadingFullScreen {...props} visible={isloading} />
@WilliamSaya-lvl30 fijate que le pasaste la prop visible, que sólo aplica al componente modal. Cambiala por isLoading así aplica tanto al modal como al loading. Después esta todo bien para mí 

![Captura desde 2023-08-14 11-56-25](https://github.com/janis-commerce/ui-native/assets/75044106/b5712b7c-aeae-40cf-9be6-a4393956623f)

2023-08-14 16:26 UTC, WilliamSaya-lvl30 commented on storybook/stories/LoadingFullScreen/LoadingFullScreen.stories.js
> +			<LoadingFullScreen {...props} visible={isloading} />
@GonzaFran Cosas que pasas cuando cambias el nombre de la variable a ultimo momento jajaja ya esta

2023-08-14 17:41 UTC, GonzaFran approved these changes

2023-08-14 19:15 UTC, pablonortiz approved these changes

2023-08-15 14:13 UTC, dam788 approved these changes

2023-08-16 12:48 UTC, christian97dd requested changes

2023-08-16 12:48 UTC, christian97dd commented on storybook/stories/LoadingFullScreen/LoadingFullScreen.stories.js
> +				<Text style={styles.TextStyles}>Open Modal</Text>
Tené en cuenta que los storybook son de cara al usuario. A menos que entre en el código, no se va a enterar que se usa un modal. Sería mejor un 'Preview loading screen'

2023-08-16 12:48 UTC, christian97dd commented on storybook/stories/LoadingFullScreen/LoadingFullScreen.stories.js
> +			<TouchableHighlight style={styles.ButtonStyle} onPress={Toogle}>
Fijate que la variable styles la estas usando antes de ser declarada

2023-08-16 12:48 UTC, christian97dd commented on src/components/LoadingFullScreen/index.tsx
> +	const hasTextPassed = Boolean(text);
en caso de que le llegue un objeto, o un array a text, esta línea va a dar true y va a intentar renderizar eso, al hacerlo va a romper, te conviene asegurarte que tambien text sea un string válido

2023-08-16 12:48 UTC, christian97dd commented on src/components/LoadingFullScreen/index.tsx
> +	...props
falta tambien mergear los estilos que vienen por fuera en el View wrapper, en caso que yo le pase estilos, va a pisar los que vos definis

2023-08-16 12:48 UTC, christian97dd commented on package-lock.json
fijate la versión que estas usando de node porque la lockFileVersion se pasó a 1. Yo uso la 16.15.0, se que algunos chicos usan tambien la 16.20.0 y funciona bien

2023-08-16 21:34 UTC, merged