Corregido Storybook del componente Text
janis-commerce/ui-native pull request #18
Opened 2023-08-14 20:33 UTC by pablonortiz

LINK DE TICKET:
https://janiscommerce.atlassian.net/browse/JUIP-113

DESCRIPCIÓN DEL REQUERIMIENTO:

Contexto

Actualmente se está tomando el componente Text de un archivo que se está armando en una carpeta del mismo nombre en la carpeta de Storybook
Necesidad

Se necesita usar el componente Text de la carpeta components, eliminando el archivo en dónde se arma el Text que se está utilizando actualmente en Storybook

DESCRIPCIÓN DE LA SOLUCIÓN:

Se eliminó el componente Text que se estaba utilizando en Storybook, por esto, se modificaron los imports del Storybook Text y StatusChip para utilizar el componente Text de la carpeta components.

Además, se modificó el componente Text, esto debido a que no estaba aceptando los props de styles correctamente, por lo que ahora se le comenzaron a pasar el resto de props que se le pasen al componente, al StyleSheet del componente.

CÓMO SE PUEDE PROBAR?
Clonar e instalar el Repo de UI-Native

Correr los siguientes 3 comandos en tres pestañas diferentes de la termina

npm run start
npm run android
npm run storybook

Se debe abrir la app en el emulador con storybooks y el navegador en la url http://localhost:7007/ donde se podrá probar
el comportamiento del componente

Para linkear el componente con un proyecto, seguir la siguiente documentación
https://fizzmod.atlassian.net/wiki/spaces/JAPP/pages/2341765125/C+mo+trabajo+con+el+package+UI

2023-08-14 21:34 UTC, dam788 approved these changes
No se como no nos dimos cuenta de eso, que mal que revisamos

2023-08-15 19:57 UTC, WilliamSaya-lvl30 requested changes

2023-08-15 19:57 UTC, WilliamSaya-lvl30 commented on src/components/Text/index.tsx
> +	style?: TextStyle[];
Creo que no es necesario pasar un array de estilos, de esta manera creo que se ve mejor, y no hay que desectructurar style.

cuando invocas un componente no se le debería pasar mas de objeto de 1 estilo. 
![Captura de pantalla de 2023-08-15 15-37-07](https://github.com/janis-commerce/ui-native/assets/69169114/30c84dea-08fd-4361-85e1-a730956e69b0)

2023-08-15 19:57 UTC, WilliamSaya-lvl30 commented on src/components/StatusChip/index.tsx
> +			{isCustomComponent ? children : <Text style={[styles(props).TextStyles]}>{children}</Text>}
Esto tendria que ver con el otro comentario, aqui no hace falta pasar los estilos como array

2023-08-17 13:48 UTC, WilliamSaya-lvl30 approved these changes

2023-08-17 20:50 UTC, christian97dd approved these changes

2023-08-17 20:50 UTC, merged