Fixed Input styles for Storybook web
janis-commerce/ui-native pull request #21
Opened 2023-08-16 12:09 UTC by pablonortiz

LINK DE TICKET:
https://janiscommerce.atlassian.net/browse/JUIP-118

DESCRIPCIÓN DEL REQUERIMIENTO:

Contexto

Actualmente, al interactuar con el Storybook web del componente Input, se está viendo cómo hay errores de estilos los cuáles hacen que no se vea cómo en el emulador

Necesidad

Se requiere corregir los estilos para que quedé cómo en el emulador

DESCRIPCIÓN DE LA SOLUCIÓN:

Cómo el label se estaba superponiendo al Input al presionarlo, se modificó el mismo para que no se muestre el label cuándo el Input reciba la prop readOnly o disabled, esto debido a que tampoco tenía sentido.

Además, se modificó la altura del label cuándo esta inactivo, la misma paso de ser de 5 a 0.

CÓMO SE PUEDE PROBAR?
Clonar e instalar el Repo de UI-Native

Correr el comando:
`npm run storybook-web`

Verificar que los estilos del Input estén correctos

**Aclaración**: Lo único que no se pudo corregir es que, al presionar un Input editable, apare un recuadro alrededor del Input, esto no puede ser corregido debido a que lo que hace la librería que se utiliza para pasar de Storybook React Native a Storybook React convierte los componentes de React Native a componentes de React, y no se permite un acceso a la propiedad de CSS de :focus del Input de React

![Captura de pantalla 2023-08-16 090715](https://github.com/janis-commerce/ui-native/assets/100979152/bb1361d1-6ca5-4118-9abb-dc4307fccfed)

2023-08-16 13:25 UTC, GonzaFran approved these changes

2023-08-16 14:45 UTC, dam788 approved these changes

2023-08-16 20:52 UTC, pablodamianberdun requested changes
@pablonortiz 

## Cuando el input tiene un `value` , se debe seguir viendo el label elevado. Sin inportar si esta onFocus on no. 
![image](https://github.com/janis-commerce/ui-native/assets/57851168/606894ca-3280-438f-8ab7-9b11b32bfbac)

efecto esperado cuando esta en `onFocus`
![image](https://github.com/janis-commerce/ui-native/assets/57851168/a5805cb4-f3ac-4dbb-9e6e-f692dc1aa4a9)

efecto esperado cuando tiene `value` pero no esta `onFocus`
![image](https://github.com/janis-commerce/ui-native/assets/57851168/a2635dfb-87a8-49c6-b6d0-12d66ee70ae1)


## Para el caso del input cuando tiene un error, se debe seguir mostrando el `value`

actual
![image](https://github.com/janis-commerce/ui-native/assets/57851168/ff51ecd6-a707-4e6c-8e55-b8f609f0f785)

esperado
![image](https://github.com/janis-commerce/ui-native/assets/57851168/ff7d7043-218e-43fe-8628-610e25a4ee73)

2023-08-17 16:58 UTC, pablonortiz commented
@pablodamianberdun ahí hice los cambios de los estilos

2023-08-17 20:02 UTC, pablodamianberdun requested changes
@pablonortiz 
## Actualizar stories del input
### Para `disabled`,  podes agregar otro que sea `disable with value`, para que se muestre un value en el input pero que no se pueda editar.

*************************************************************************

### En la del error, falta mostrar un value. Se muestra el mensaje  'invalid name' pero no estamos mostrando cual es ese nombre que no es válido.
![image](https://github.com/janis-commerce/ui-native/assets/57851168/d5bbbb2c-45d9-4052-9292-2cdcb8cbe6ed)


Tiene que tener este mismo efecto
![image](https://github.com/janis-commerce/ui-native/assets/57851168/7dfaa86c-d360-4353-9b5f-df36722125f1)

el value se debe poder editar desde el input y cuando se haga onBlur() , se muestra nuevamente el error

2023-08-18 15:40 UTC, pablonortiz commented
@pablodamianberdun ahí acabo de subir los cambios

2023-08-23 16:24 UTC, pablodamianberdun approved these changes

2023-08-23 18:45 UTC, merged