crear componente icon
janis-commerce/ui-native pull request #22
Opened 2023-08-24 15:53 UTC by dam788

**Link de Tarea:**
https://janiscommerce.atlassian.net/browse/JUIP-85

**Link de Subatarea:**
https://janiscommerce.atlassian.net/browse/JUIP-119

**Contexto:**
Actualmente no contamos con un componente Icon reutilizable, por lo que nos obliga en todas las apps a tener código repetido, y en caso de querer hacer alguna modificación, se deberá cambiar en las 3 apps por igual.

**Necesidad:** 
Tener el componente Icon reutilizable disponible en el package UI para facilitar su escalabilidad

**Props que debe aceptar:**

Prop | Default | Requerido | Tipo | Obs
-- | -- | -- | -- | --
name |   | true | string |  
color | #2979FF | false | string | tomar el color por default de la paleta del package
size | 16 | false | number |  

**Análisis funcional**

1. Instalar el package  react-native-vector-icons
2. Seguir la instalación para android y ios [GitHub - oblador/react-native-vector-icons: Customizable Icons for React Native with support for image source and full styling.](https://github.com/oblador/react-native-vector-icons) : necesitamos el archivo iconmoon.ttf  y selection.json. El asset se puede descargar desde: 
                        - [Assets Apps](https://janiscommerce.atlassian.net/wiki/spaces/JAPP/pages/2312437761/Assets+Apps) 
3. Crear el componente Icon
4. Crear muestrario de iconos en Icon.stories.js

**Como se puede probar?:**
- Linkear package con yalc -> https://janiscommerce.atlassian.net/wiki/spaces/JAPP/pages/2341765125/C+mo+trabajo+con+el+package+UI
- importar componente dentro de alguna app de janis:

```
import {Icon} from '@janiscommerce/ui-native';

...
<Icon name="iso_janis" size={60} />

```

**Screenshoots**

![1 - icons](https://github.com/janis-commerce/ui-native/assets/60529414/b371864c-89cb-4667-a2d7-274994c35b5d)

2023-08-24 17:15 UTC, pablonortiz requested changes

2023-08-24 20:35 UTC, pablonortiz approved these changes

2023-08-28 21:14 UTC, GonzaFran requested changes
El componente funciona excelente, faltaría pullearse master a la branch para corregir este problema que está pasando cuando tratas de ver los colores desde android. Falta eso nada más y estaríamos.

![Peek 2023-08-28 17-26](https://github.com/janis-commerce/ui-native/assets/75044106/276fe0cd-155a-44c6-92f0-efe1da8e6434)

2023-08-30 21:09 UTC, GonzaFran approved these changes

2023-09-15 13:53 UTC, christian97dd requested changes
Dami!, estuve probando de linkear delivery con ui native eliminando la fuente de íconos para ver si seguía funcionando. No funcionó :p
![image](https://github.com/janis-commerce/ui-native/assets/49655553/721ed370-7b09-4c5e-8725-1005597697fa)
La semana que viene nos juntamos para ver como podemos hacer, porque estuve probando también un par de alternativas, pero no funcionaron

2023-10-17 19:10 UTC, christian97dd approved these changes

2023-10-17 19:12 UTC, merged