Fix/j UI p 124 loading
janis-commerce/ui-native pull request #23
Opened 2023-09-19 14:28 UTC by WilliamSaya-lvl30

### **Link de Tarea:**
https://janiscommerce.atlassian.net/browse/JUIP-124

### **Contexto**:
Luego del lanzamiento de la primera version de la libreria ui-native y de su implementación en las apps, nos reportan que en dispositivos pequeños y versiones de android 7 el loadingFullScreen no esta funcionando como se esperaba.

![loading-bug](https://github.com/janis-commerce/ui-native/assets/69169114/8e02206b-fee8-4f8a-9370-ba9f4524087c)

### **Necesidad**:
Debe funcionar correctamente en todos los dispositivos

### **Análisis funcional**
Para replicar el bug se tuvo que usar un telefono pequeño con android 7, el error esta siendo ocacionando por el estilo borderRadius del Animated view, en el componente loading, si se elimina ese estilo la animacion sigue funcionando bien.

![loading-cuadrado](https://github.com/janis-commerce/ui-native/assets/69169114/83ccaf89-a316-48ad-8ad1-e6a20f52027c)

Dejo evidencia del issues encontrado al respecto
[Rotate transform not working well on View with borderRadius · Issue #18266 · facebook/react-native](https://github.com/facebook/react-native/issues/18266) 
[View bounds and touchable area incorrect after a rotate or a scale transform · Issue #19637 · facebook/react-native](https://github.com/facebook/react-native/issues/19637) 
Este problema se presenta en estas versiones de android (v7 ~ v9)

No encontré alguna solución para esto, así que se pensó otra solución.

Para solucionar esto se probara colocar el loading como un svg, manteniendo la misma animación.

### **Como se puede probar?:**
En android estudio crear un Device con un android 7 
Levantar el package en master para replicar el bug
luego levantar el package en la rama fix para ver que funciona correctamente

### **Screenshoots**

![evidencia-bug-loading](https://github.com/janis-commerce/ui-native/assets/69169114/0fba1c07-151c-4482-adab-ebca386d51cb)

2023-09-19 15:58 UTC, dam788 approved these changes
Anda joya
![Peek 2023-09-19 12-54](https://github.com/janis-commerce/ui-native/assets/60529414/f08d370f-9141-49c3-a249-2988fffccbd0)

2023-09-19 16:22 UTC, pablonortiz approved these changes
Lo estuve probando en emulador con Android 8 y va joya!

2023-09-19 22:05 UTC, christian97dd requested changes
quedó roto el LoadingFullScreen en web:
![loadingFullScreen-web](https://github.com/janis-commerce/ui-native/assets/49655553/2ed23580-2786-48b7-bb45-9d57b98a5ff4)

2023-09-20 18:05 UTC, WilliamSaya-lvl30 commented on package-lock.json
Me manejo con nvm y uso la versión requerida en el package que es 16.20, al correr npm i se actualizo el package.lock

2023-09-27 20:32 UTC, merged