Added possibility to change between app mode and storybook app mode
janis-commerce/ui-native pull request #29
Opened 2023-11-22 17:34 UTC by pablonortiz

**LINK DE TICKET:**

https://janiscommerce.atlassian.net/browse/JUIP-133

**DESCRIPCIÓN DEL REQUERIMIENTO:**

Se requiere contar con la posibilidad de intercambiar entre la app de React Native, para así poder testear los componentes de una manera más fácil, y también poder ingresar en modo storybook.

**DESCRIPCIÓN DE LA SOLUCIÓN:**

Se añadió la librería https://www.npmjs.com/package/react-native-config ya que la misma se necesita para poder leer las variables del entorno.

A su vez, se creó el script set-app-mode.js, el cuál se encarga de escribir en el archivo .env si la key LOAD_STORYBOOK estará en true o false. En este sentido, se modificó el package.json, estos fueron los cambios que se hicieron:

- El comando npm run android fue modificado para levantar el modo app en Android.
- El comando npm run ios fue modificado para levantar el modo app en iOS
- Se añadió el comando storybook:android para levantar la app en modo Storybook en Android.
- Se añadió el comando storybook:ios para levantar la app en modo Storybook en iOS.
- Se modificó el comando npm run storybook, cambiándolo por npm run storybook-server, para evitar confusiones.

Finalmente, se modificó el archivo index.js para cargar Storybook o la App dependiendo de la variable del entorno.

**CÓMO SE PUEDE PROBAR?**

Corriendo los comandos mencionados anteriormente:
npm run android para correr el modo app y npm run storybook:android para correr el modo storybook.

2023-11-22 21:10 UTC, dam788 approved these changes
Anda joya

2023-11-27 19:07 UTC, WilliamSaya-lvl30 requested changes

2023-11-27 19:07 UTC, WilliamSaya-lvl30 commented on index.js
> +const Component = Config.LOAD_STORYBOOK === 'true' ? Storybook : App;
LOAD_STORYBOOK ya es un booleano, es redundante compararlo con true.
Deberia quedar asi 
const Component = Config.LOAD_STORYBOOK ? Storybook : App;

2023-11-29 13:07 UTC, christian97dd requested changes
dejé unos comentarios, la idea es volar la librería de rn config

2023-11-29 13:07 UTC, christian97dd commented on scripts/set-app-mode.js
> +fs.writeFileSync('.env', `LOAD_STORYBOOK=${!!modes[mode]}`);
nico, para no depender de la librería de rn config, aca lo que te conviene hacer es crear un archivo que en vez de .env, se llame env.json, donde setees la key LOAD_STORYBOOK. Entonces cuando queres levantarla, la levantas desde ese archivo, como hacemos en las apps, fijate que al correr cada ambiente (beta, qa y master), setteamos un env json distinto.
y acordate tambien de agregarlo al gitignore, cosa de que no se suba el archivo

2023-11-29 13:07 UTC, christian97dd commented on android/app/build.gradle
> +apply from: project(':react-native-config').projectDir.getPath() + "/dotenv.gradle"
aca deberías de volar esta linea

2023-11-29 13:07 UTC, christian97dd commented on index.js
> +import Config from 'react-native-config';
aca es donde te importas la key que vos necesitas, pero de env.json

2023-11-29 13:07 UTC, christian97dd commented on .env
> +LOAD_STORYBOOK=true
este archivo de .env, vuela

2023-11-29 13:07 UTC, christian97dd commented on .gitignore
> +.env
aca sería meter al env.json

2023-11-29 13:41 UTC, pablonortiz commented
@christian97dd ahí hice los cambios

2023-12-05 17:55 UTC, merged