Appsrn 250 agregar escala y corregir componentes
janis-commerce/ui-native pull request #30
Opened 2023-11-28 13:27 UTC by dam788

### LINK DE TICKET:

https://janiscommerce.atlassian.net/browse/APPSRN-247

### DESCRIPCIÓN DEL REQUERIMIENTO:

**Contexto**

Actualmente, en varios archivos de la aplicación, se está usando la función getScale para el diseño de componentes y está función no funciona correctamente, por lo que ya se pudieron observar distintos casos en los que el diseño se ve mal según el dispositivo, cómo lo fue el caso de JDAPP-1033

**Necesidad**

Analizar la forma apropiada para que los diseños se vean correctamente en todos los dispositivos, ya sea modificando o eliminando la función getScale

### DESCRIPCIÓN DE LA SOLUCIÓN:

Se analizó:

```

import {Dimensions, PixelRatio, Platform} from 'react-native';

const guidelineBaseWidth = 350;
const guidelineBaseHeight = 680;

export const IS_IOS = Platform.OS === 'ios';
export const {width: viewportWidth, height: viewportHeight} =
  Dimensions.get('window');

export const {width: screenWidth, height: screenHeight} =
  Dimensions.get('screen');

export const horizontalScale = (size?: number): number =>
  PixelRatio.roundToNearestPixel(
    (screenWidth / guidelineBaseWidth) * (size ?? 1),
  );
export const verticalScale = (size?: number): number =>
  PixelRatio.roundToNearestPixel(
    (screenHeight / guidelineBaseHeight) * (size ?? 1),
  );
export const moderateScale = (size: number, factor = 0.5): number =>
  size + (horizontalScale(size) - size) * factor;

export const isSmallDevice: boolean = viewportWidth <= 365;

```

Y se encontró esta documentación que fue de mucha utilidad para realizar pruebas ( **[LINK](https://medium.com/simform-engineering/create-responsive-design-in-react-native-f84522a44365)** ), y la diferencia entre uno y otro casi no existe, pero si indica el uso correcto de las funciones de escalado donde: 
![image](https://github.com/janis-commerce/ui-native/assets/60529414/9eb08f79-9298-4d40-8c8f-35b81ed6acc9) ... donde nos encontramos con **moderateScale** que nos sirve para hacer un escalado proporcional en todas las pantallas (siempre y cuando su factor sea 1) y un escalado progresivo utilizando factor 0.5

- En base a ésto, tomamos los componentes para escalarlos con **moderateScale** y procedimos a reemplazarlo en todos lados donde pueda realizarse la comparación de componentes en diferentes dispositivos.
**[Pruebas en ésta rama](https://bitbucket.org/fizzmodsrl/janis-wms-app/branch/pruebas-scale-ratio)**

**Importante:**
- Se creo una util llamada **scaledForDevice**, que en base al archivo de env.json chequea el estado de WEB_MODE (true/false), con ésta key validamos si necesitamos utilizar las utils que escalan el tamaño en dispositivo o no, ya que en versión web no necesitamos escalar los componentes. Para su correcto funcionamiento se modificaron los archivos de script que crea el env.json y algunas configuraciones del repo. Se modificaron los script de **storybook-web** y **storybook-web-build**
- Se agregó una pequeña corrección en **RadioButton**

### CÓMO SE PUEDE PROBAR?

1. Correr dos emuladores con el comando `npm start `y` npm run storybook:android,` ejemplo **Nexus S (480x800)** y **Pixel 7 (1080x2400)**.
2. realizar comparaciones en los mismos componentes para ver si están escalados al mismo tamaño en la pantalla en los emuladores. _(Si tiene un celular fisico puede correrlo tambien)_
3. verificar el funcionamiento de **storybook-web** corriendo el comando `npm start `y `npm run storybook-web`
4. verificar el funcionamiento de  **storybook-web-build**. Correr comandos **npm run build** y acceder a la carpeta **dist/index.js** para verificar que hay hecho correctamente el build.

### SCREENSHOTS:

Sin Escala:
![1 - som escala](https://github.com/janis-commerce/ui-native/assets/60529414/f2a87ce2-35f2-40cc-be70-a1e465786573)
Con Escala:
![1](https://github.com/janis-commerce/ui-native/assets/60529414/59ae4392-badb-42f3-bc58-89480c6ff0da)

----

Sin escala:
![2 - sin modelar escala](https://github.com/janis-commerce/ui-native/assets/60529414/27cfded3-f2f9-46e3-acf8-ee08b2978357)
Con Escala:
![2](https://github.com/janis-commerce/ui-native/assets/60529414/48660d4b-d605-4e17-8968-212bdca9ddfa)

-----

Sin Escala:
![3 - sin modelar escala](https://github.com/janis-commerce/ui-native/assets/60529414/3bbf475c-4bfd-45dc-9113-dd5b539d4643)
Con Escala:
![3](https://github.com/janis-commerce/ui-native/assets/60529414/749136e3-2e38-4496-ba94-66a7140930ac)

-----

Sin Escala:
![4-sin modelar escala](https://github.com/janis-commerce/ui-native/assets/60529414/0f81b9e9-21d3-49d2-9ef0-4bb2e6f29ac2)
Con Escala:
![4](https://github.com/janis-commerce/ui-native/assets/60529414/775fb7b0-84d6-4271-a71d-808d6a52d739)

-----

Con Escala:
![5](https://github.com/janis-commerce/ui-native/assets/60529414/7d67bf3b-59fd-4e4c-817d-e4acd5518330)

-----

Con Escala:
![6](https://github.com/janis-commerce/ui-native/assets/60529414/dac31db9-086b-4ad7-8bd6-8291c2941644)

### DATOS EXTRA A TENER EN CUENTA:

2023-11-28 21:51 UTC, GonzaFran commented on src/components/CheckBox/index.tsx
> +			width: moderateScale(customSize),
@dam788 según lo que planteaste de la documentación, en este caso no se debería usar horizontalScale? lo mismo para height con verticalScale

2023-11-28 22:03 UTC, GonzaFran commented on src/scale/index.ts
> +	isIOS,
`isIOS` se esta exportando como un booleano pero no tiene impacto en el funcionamiento de las funciones de escala, tiene sentido exportarlo? mismo caso con smallDevice.

2023-11-28 22:05 UTC, GonzaFran commented on storybook/stories/DesignStystem/Icons.stories.js
> +import {moderateScale} from '../../../src/utils';
@dam788 acá, y en todas las stories que usan moderateScale o sus variantes, se tiene que cambiar la importación de `src/utils` a `src/scale`

2023-11-28 23:53 UTC, GonzaFran requested changes
Se dejaron comentarios en el PR

2023-11-29 17:00 UTC, pablonortiz approved these changes
Lo estuve probando y lo vi bien

2023-12-20 13:12 UTC, christian97dd requested changes
Fijate que te quedaron mal los storybooks en web de algunos componentes:
![image](https://github.com/janis-commerce/ui-native/assets/49655553/8ffdabab-9c52-441f-9bab-9f284c1280c6)
el Loading y algunos mas también. Si voy a master se ven lo mas bien

2024-01-09 16:12 UTC, GonzaFran commented on src/components/Carousel/index.tsx
> +			width: validateWidth,
En este caso se debe dejar la propiedad width como valor para la key del mismo nombre, ya que con la modificación el componente se muestra así en la versión mobile:

![Captura desde 2024-01-09 12-29-12](https://github.com/janis-commerce/ui-native/assets/75044106/ae1e1754-ff4e-412e-b7a0-be7ab38b9c61)

Después de lo que hablamos y las pruebas que hicimos deberíamos dejar el código de la siguiente manera para que se vuelva a centrar la página en dispositivos de mayor resolución:

![Captura desde 2024-01-09 12-45-42](https://github.com/janis-commerce/ui-native/assets/75044106/ac4ab3e1-f354-4920-b708-243e66d62646)
![Captura desde 2024-01-09 13-12-11](https://github.com/janis-commerce/ui-native/assets/75044106/63cd7f02-8ff4-4047-8001-a5564e1a9ab4)

2024-01-09 16:17 UTC, GonzaFran commented
@dam788 estuve revisando la mayoría de los componentes que podían llegar a tener problemas de escala al intercambiar entre mobile y web y se ven bien. Gran laburo!

Se deja una corrección para carousel, por el resto lo vi bien; quedaría pendiente agregar en el PR lo siguiente:

Cuando inicie la app lo primero que se me mostró fue esta pantalla:

![Captura desde 2024-01-09 12-11-49](https://github.com/janis-commerce/ui-native/assets/75044106/237f86de-2dfd-4921-a015-0d5df13d89b9)

Esto se debe a cómo están armados los comandos del package.json; agregate una aclaración en el PR para explicar la diferencia entre usar npm run android y npm run storybook:android (nada muy extenso, sólo explicar para qué usar cada uno)

2024-01-09 16:17 UTC, GonzaFran requested changes
Se dejó un comentario en el componente Carousel

2024-01-09 16:27 UTC, WilliamSaya-lvl30 approved these changes

2024-01-09 18:43 UTC, GonzaFran approved these changes

2024-01-11 16:40 UTC, christian97dd approved these changes

2024-01-11 16:41 UTC, merged