J UI p 142 crear componente fullscreen message
janis-commerce/ui-native pull request #34
Opened 2024-02-22 23:24 UTC by dam788

### LINK DE TICKET:
https://janiscommerce.atlassian.net/browse/JUIP-139

### LINK SUBTAREA:
https://janiscommerce.atlassian.net/browse/JUIP-142

### DESCRIPCIÓN DEL REQUERIMIENTO:

**Contexto**
Revisando los diseños de delivery y WMS, encontré que este componente se repite en ambas apps y no se si en picking tambien. El equipo de diseño en una demo, indicó que este componente quieren empezar a implementarlo en las apps

**Necesidad**
Para evitar tener código repetido, se requiere pasar el componente al package ui-native

### DESCRIPCIÓN DE LA SOLUCIÓN:
- Se creo componente con las siguientes props

**Props que debe aceptar:**

Prop | Default | Requerido | Tipo | Obs.
-- | -- | -- | -- | --
backgroundColor | - | si | string | color de fondo
isVisible | false | no| boolean | es visible o no
title | - | si | string | texto de titulo
subtitle | " " | no | string | texto de subtitulo
iconName | " " | string | string |   nombre de icono
textsColor | #FFF | no | string | color de textos
iconColor | #FFF | no | function | color de icono
animationType | '' | no | enum('slide', 'fade', 'enum') | animación de componente
children | null | no | ReactElement | recibe componentes customs

### CÓMO SE PUEDE PROBAR?

**Correr en alguna de las apps:**
1. correr en ui-native el comando: `yalc push && yalc puclish`
2. correr en una de las apps el comando `yalc add @janis-commerce/ui-native` y `npm i`
3. agregar el componente y probar que funcione correctamente.

**Correr en storybook:**

1. correr en ui-native `npm start` y `npm  run storybook:android` para verlo en el emulador.
2. correr en ui-native `npm run storybook-web` para verlo en el navegador.

### SCREENSHOTS:

![Peek 2024-02-22 20-18](https://github.com/janis-commerce/ui-native/assets/60529414/c0cd4b97-02e9-41f6-88f2-12b77fc8d29a)

### DATOS EXTRA A TENER EN CUENTA:

CHANGELOG:

2024-02-23 19:43 UTC, pablonortiz requested changes
@dam788 te dejé unos comentarios y también te faltó exportar el componente en la librería, tenés que meter el componente en src/index.ts junto al resto de los componentes del package, cualquier cosa avisame!

2024-02-23 19:43 UTC, pablonortiz commented on src/components/FullScreenMessage/index.tsx
> +	children?: ReactElement | null;
Acá estarían faltando dos props, una sería duration, porque el componente mismo debería renderizar por cierto tiempo el componente a partir de la prop duration, esa lógica no debería hacerse por afuera cómo quedó en su Storybook con:

```
const Toogle = () => {
		setVisible(true);
		setTimeout(() => {
			setVisible(false);
		}, 3000);
	};
```

Y la otra prop debería ser onEndDuration, el cuál sería un callback a ejecutarse una vez que se cumpla la duration y se deje de renderizar el componente

2024-02-26 19:37 UTC, pablonortiz commented
@dam788 te faltó exportar el componente en la librería para poder linkearlo con las apps, tenés que meter el componente en src/index.ts junto al resto de los componentes

2024-02-26 19:57 UTC, pablonortiz requested changes
@dam788  Estuve probando y funca joya, pero hay un problema con el onEndDuration, estuve probando el componente, pasándole una función a esa prop y el tema es que se ejecuta perfectamente al terminar el duration, pero el problema es que se está ejecutando también cuándo se renderiza el componente por primera vez, por lo que se está ejecutando 2 veces en vez de 1

2024-02-27 18:27 UTC, GonzaFran approved these changes

2024-02-28 12:52 UTC, christian97dd requested changes
se deja un comentario

2024-02-28 13:49 UTC, dam788 commented on src/components/FullScreenMessage/index.tsx
> +	useEffect(() => {
fijate que una es isVisible que vine por props, y la otra es visible y setVisible que son del useState.

2024-02-28 16:25 UTC, pablonortiz approved these changes
Ahí lo estuve probando y va joya, ahora sí se está ejecutando una sola vez el onEndDuration

2024-03-06 14:24 UTC, christian97dd commented on src/components/FullScreenMessage/index.tsx
> +	useEffect(() => {
Claro, son 2 variables distintas, pero a lo que voy es que hay una que está de mas.
Probé lo que me comentaste en slack y funciona joya, pero te propongo una mejora:
Fijate que vos recibís la prop `isVisible` y la usas para cambiar el valor de tu state. A lo que voy, es que te conviene directamente volar esa prop y manejarte con el state que tenes en el componente. De esa manera, solo en el componente te va a quedar un useEffect con el array de deps vacío y con el setTimeout de la key duration que pase tu state a false y ejecute la prop onEndDuration.

2024-03-06 18:25 UTC, christian97dd commented on src/components/FullScreenMessage/index.tsx
> +	useEffect(() => {
Dami, revisando lo que hablamos hoy en la call, haciendo esto en el componente:
```
import React, {FC, ReactElement, useEffect} from 'react';
import {Modal, StyleSheet, View} from 'react-native';
import {moderateScale, scaledForDevice} from '../../scale';
import {base, primary} from '../../theme/palette';
import Icon from '../Icon';
import Text from '../Text';

export enum animationTypes {
	Slide = 'slide',
	Fade = 'fade',
	None = 'none',
}

interface Props {
	backgroundColor?: string;
	isVisible?: boolean;
	title?: string;
	subtitle?: string;
	iconName?: string;
	textsColor?: string;
	iconColor?: string;
	animationType?: animationTypes;
	duration?: number;
	onEndDuration?: () => void;
	children?: ReactElement | null;
}

const FullScreenMessage: FC<Props> = ({
	backgroundColor = primary.main,
	title = '',
	isVisible = false,
	subtitle = '',
	iconName = '',
	textsColor = base.white,
	iconColor = base.white,
	animationType = animationTypes.Slide,
	duration = 3000,
	onEndDuration = () => {},
	children = null,
	...props
}) => {
	const validTitle = !!title && typeof title === 'string';
	const validSubtitle = !!subtitle && typeof subtitle === 'string';
	const validIconName = !!iconName && typeof iconName === 'string';

	const validPaddingHorizontal = scaledForDevice(50, moderateScale);
	const validMarginBottomTitle = scaledForDevice(30, moderateScale);
	const validMarginBottomSubtitle = scaledForDevice(50, moderateScale);
	const validFontTitle = scaledForDevice(32, moderateScale);
	const validFontSubtitle = scaledForDevice(16, moderateScale);
	const validLineHeightTitle = scaledForDevice(40, moderateScale);

	const styles = StyleSheet.create({
		container: {
			justifyContent: 'center',
			alignItems: 'center',
			width: '100%',
			height: '100%',
			backgroundColor: backgroundColor,
		},
		title: {
			fontWeight: 'bold',
			textAlign: 'center',
			color: textsColor,
			paddingHorizontal: validPaddingHorizontal,
			marginBottom: validMarginBottomTitle,
			fontSize: validFontTitle,
			lineHeight: validLineHeightTitle,
		},
		subtitle: {
			textAlign: 'center',
			color: textsColor,
			paddingHorizontal: validPaddingHorizontal,
			marginBottom: validMarginBottomSubtitle,
			fontSize: validFontSubtitle,
		},
	});

	useEffect(() => {
		setTimeout(() => {
				onEndDuration();
			}, duration);
	}, []);

	return (
		<Modal visible={isVisible} animationType={animationType} transparent {...props}>
			<View style={styles.container}>
				{children ?? (
					<>
						{validTitle && <Text style={styles.title}>{title}</Text>}
						{validSubtitle && <Text style={styles.subtitle}>{subtitle}</Text>}
						{validIconName && <Icon color={iconColor} size={130} name={iconName} />}
					</>
				)}
			</View>
		</Modal>
	);
};

export default FullScreenMessage;
```

Me funcionó bien sin usar los 2 useEffects y sin el useState dentro del componente. Tené en cuenta que cuanto más evitemos el uso del useState, mejor porque ganamos performance evitando re renders. 
Despues del lado de cualquier app, el código queda igual que antes:
`<FullScreenMessage isVisible={isVisible} onEndDuration={() => setVisible(false)} title='Janis'/>`

2024-03-06 18:26 UTC, christian97dd commented on src/components/FullScreenMessage/index.tsx
> +	useEffect(() => {
Ya que estamos, dejo evidencia de que funciona :p
![Peek 2024-03-06 15-21](https://github.com/janis-commerce/ui-native/assets/49655553/52e616cf-81d0-44f8-bf2d-d18be1454c19)

2024-03-07 13:04 UTC, christian97dd requested changes
Dami, fijate que al probar con storybooks no se oculta nunca el componente
![image](https://github.com/janis-commerce/ui-native/assets/49655553/9c159db9-cd2e-4547-9018-678113e7009c)
y tampoco le puedo pasar un duration custom:
![image](https://github.com/janis-commerce/ui-native/assets/49655553/c2028015-f885-480e-8605-98b8f7d68e90)

2024-03-07 14:10 UTC, dam788 commented
@christian97dd se actualizó las dependencias de useEffect, porque el onEndDuration solo debe activarse cuando el valor de isVisible es true.

2024-03-07 14:28 UTC, christian97dd requested changes
Fijate que sigue faltando la prop duration en storybooks para poder modificarla desde ahí. Faltaría solo agregarla en este objeto de storybooks:
![image](https://github.com/janis-commerce/ui-native/assets/49655553/1422f4d7-c55d-4b40-8d09-ee5fb62be220)

2024-03-07 16:41 UTC, christian97dd approved these changes

2024-03-07 16:42 UTC, merged