JUIP-148 Crear componente Button
janis-commerce/ui-native pull request #35
Opened 2024-04-16 20:51 UTC by dam788

### LINK DE TICKET: 
https://janiscommerce.atlassian.net/browse/JUIP-143

### DESCRIPCIÓN DEL REQUERIMIENTO: 

**Contexto**
Actualmente tenemos un boton en la libreria que lo conocemos como BaseButton que hace todo.

**Necesidad**
Crear un nuevo componente de botón  que pueda ser utilizado dentro de la librería de componentes existente. Este botón debe tener la capacidad de aceptar varias propiedades para personalizar su apariencia y comportamiento, incluyendo variantes de estilo, colores personalizados y la opción de incluir un icono.

¿Qué necesitamos lograr con este botón? Nuestro objetivo es desarrollar un botón versátil que pueda adaptarse a diferentes estilos de diseño y necesidades de nuestras aplicaciones. Queremos que sea una herramienta poderosa que nos ayude a mantener una apariencia coherente en todas nuestras aplicaciones, al tiempo que nos permite reutilizar fácilmente el código.
Características del botón:

**Estilos adaptables:**

El botón debe admitir dos estilos diferentes: "outlined" , "contained" y “text“. Esto nos permitirá usarlo en una variedad de contextos y respetar las especificaciones de diseño de cada aplicación.

**Personalización de colores:**

Utilizaremos la paleta de colores existente, que incluye colores primarios, secundarios, grises y de estado. Esto asegurará que el botón se integre perfectamente en nuestras aplicaciones y mantenga una apariencia coherente en todo momento.

**Soporte para iconos:**

El botón debe ser capaz de incluir un icono, ya sea antes o después del texto. La inclusión de iconos es opcional, pero necesaria en ciertos casos.

**Objetivos:**

Facilitar el trabajo del equipo al proporcionar un botón que sea fácil de integrar y personalizar en nuestras aplicaciones.

Promover la reutilización de código y mantener una apariencia coherente en todas nuestras aplicaciones.

Brindar una oportunidad de aprendizaje y crecimiento para el desarrollador encargado de esta tarea.

 

**Que vamos a conseguir con esto?**
No vamos a usar mas el BaseButton exportandolo desde la libreria, sino que el componente Button lo usara internamente como base para extender y usaremos en las distintas apps el componente Button. (Tener en cuenta comentario mas abajo que el cambio tiene que ser retro)

Contar con un boton nuevo que permita mediante props mostrarlo segun el diseño planteado en los rediseños.

### DESCRIPCIÓN DE LA SOLUCIÓN: 

- se modificó BaseButton para llevarlo a la minima expresión del cual podemos extender para crear nuevos desarrollo de botón según convenga.
- Se creó el componente Button el cual posee las siguientes props:

![2024-04-16_17-39](https://github.com/janis-commerce/ui-native/assets/60529414/ee27a750-8ee4-4b00-b9d7-2ba13f5b5b48)

### CÓMO SE PUEDE PROBAR? 

**Desde ui-native:**

- Copiamos esto en App.tsx:

```
import React from 'react';
import {View} from 'react-native';
import Button, {Color, Type, Variant, IconPosition} from './src/components/Button';

const App = () => (
	<View style={{padding: 20, flexDirection: 'row'}}>
		<Button
			// value='CANCEL'
			icon="box"
			isLoading={false}
			type={Type.Main}
			variant={Variant.Contained}
			color={Color.Primary}
			// iconPosition={IconPosition.Right}
			disabled={false}
			// style={}
		/>
		<Button
			value="Button"
			icon="box"
			isLoading={false}
			type={Type.Main}
			variant={Variant.Outlined}
			color={Color.Primary}
			iconPosition={IconPosition.Left}
			disabled={false}
			style={{marginLeft: 6, flex: 1}}
			iconStyle={{color: 'red', fontSize: 30}}
		/>
	</View>
);

export default App;
```

- Ahora tiramos los comandos: `npm start` y `npm run android`

**Desde storybook:**

- Tirar comando: `npm start `y `npm run storybook:android`

**Desde una de la app:**

- Tirar comando `yalc push && yalc puckis`h en **ui-native** .
- En la app que quieras probar: yalc add `@janiscommerce/ui-native` y `npm i`.

### SCREENSHOTS:
![Peek 2024-04-16 17-46](https://github.com/janis-commerce/ui-native/assets/60529414/31d78323-f5e3-4ead-a67c-00aa554ff9e8)

### LINK PR QA:

### DATOS EXTRA A TENER EN CUENTA:

### CHANGELOG:

2024-04-16 21:35 UTC, pablonortiz approved these changes
Lo estuve probando en Delivery y lo vi bien, me parece perfecto cómo fuiste sacando la lógica en distintas utils y constantes, lo que dejo el componente bastante limpio y legible

2024-04-17 13:17 UTC, GonzaFran requested changes
@dam788 lo probé en WMS y lo vi muy bueno, lo único que agregaría sería que, en las props, te sugiera opciones para usar en las propiedades [variant, color, iconPosition, etc.], algo así:
![Captura desde 2024-04-17 09-54-01](https://github.com/janis-commerce/ui-native/assets/75044106/350abb01-efc7-4c9d-9ee9-2c6c4ef4d49b)

Fijate que pablo lo había armado para el componente avatar. Si es fácil de adaptar buenisimo, si es mucho laburo dejalo así, pero creo que facilita mucho su uso si te sugiere valores para las props.
Cualquier cosa avisame y lo vuelvo a ver.

2024-04-17 13:17 UTC, GonzaFran commented on src/components/Button/theme/configs/index.ts
> +export const stlyeConfig = {
@dam788 una pavada, quedó mal el nombre

2024-04-17 19:11 UTC, Maukr requested changes
Hola @dam788 3 cosas que noté haciendo pruebas:
1- El type secondary y type primary cambian el alto del botón, esto es esperado?
Prueba:
```
		<Button
			value="Button with Box Icon"
			icon="box"
			isLoading={false}
			type={'secondary'}
			variant={'outlined'}
			color={'primary'}
			iconPosition={'left'}
			disabled={false}
			style={{marginLeft: 6}}
		/>
		<Button
			value="Button with Box Icon"
			icon="box"
			isLoading={false}
			type={'main'}
			variant={'outlined'}
			color={'primary'}
			iconPosition={'left'}
			disabled={false}
			style={{marginLeft: 6}}
		/>
```
![image](https://github.com/janis-commerce/ui-native/assets/61480380/ee3a235e-ad3f-47cf-93e1-f715e20dcd46)

2- La prop color solo funciona para la variante por defecto? Si quiero poner success con la variante "outlined" no estaría haciendo efecto, no cambia a verde la font y el ícono.

Prueba:
```
<Button
			value="Button with Box Icon"
			icon="box"
			isLoading={false}
			type={'main'}
			variant={'outlined'}
			color={'success'}
			iconPosition={'left'}
			disabled={false}
			style={{marginLeft: 6}}
		/>
```
![image](https://github.com/janis-commerce/ui-native/assets/61480380/bb53a5ac-6f0a-495f-ab96-7ffa94d79cad)

3- Esto es un detalle, por algún motivo en especial se definió que el "value" por defecto sea "Button"? No sería mejor que no aparezca nada así no tenemos que enviarlo como null?

2024-04-17 20:05 UTC, dam788 commented
> Hola @dam788 3 cosas que noté haciendo pruebas: 1- El type secondary y type primary cambian el alto del botón, esto es esperado? Prueba:
> 
> ```
> 		<Button
> 			value="Button with Box Icon"
> 			icon="box"
> 			isLoading={false}
> 			type={'secondary'}
> 			variant={'outlined'}
> 			color={'primary'}
> 			iconPosition={'left'}
> 			disabled={false}
> 			style={{marginLeft: 6}}
> 		/>
> 		<Button
> 			value="Button with Box Icon"
> 			icon="box"
> 			isLoading={false}
> 			type={'main'}
> 			variant={'outlined'}
> 			color={'primary'}
> 			iconPosition={'left'}
> 			disabled={false}
> 			style={{marginLeft: 6}}
> 		/>
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/61480380/323348934-ee3a235e-ad3f-47cf-93e1-f715e20dcd46.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODM5MDgsIm5iZiI6MTcxMzM4MzYwOCwicGF0aCI6Ii82MTQ4MDM4MC8zMjMzNDg5MzQtZWUzYTIzNWUtYWQzZi00N2NmLTkzZTEtZjcxNWUyMGRjZDQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE5NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTljODRjZWYxNjRjODljYjU1MWE0MjRmY2Y1YTA1MWY0MmNkN2UzNDA2YWQ3YzhkOWYzMjZjNWQ4OTJlOWUwYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XB73J_f2ALzS7I0_qUsYgJbwGpCyGGfaIIQ9OIKVJzc)
> 
> 2- La prop color solo funciona para la variante por defecto? Si quiero poner success con la variante "outlined" no estaría haciendo efecto, no cambia a verde la font y el ícono.
> 
> Prueba:
> 
> ```
> <Button
> 			value="Button with Box Icon"
> 			icon="box"
> 			isLoading={false}
> 			type={'main'}
> 			variant={'outlined'}
> 			color={'success'}
> 			iconPosition={'left'}
> 			disabled={false}
> 			style={{marginLeft: 6}}
> 		/>
> ```
> 
> ![image](https://private-user-images.githubusercontent.com/61480380/323349482-bb53a5ac-6f0a-495f-ab96-7ffa94d79cad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzODM5MDgsIm5iZiI6MTcxMzM4MzYwOCwicGF0aCI6Ii82MTQ4MDM4MC8zMjMzNDk0ODItYmI1M2E1YWMtNmYwYS00OTVmLWFiOTYtN2ZmYTk0ZDc5Y2FkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDE5NTMyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThiMTY2YmMxOGVhNWRlOGY0NzEzM2Y0Y2MzY2QzMGVjNmUzNmE4M2JiMDkxYmM1MTIyNjAyNWI4NDBmYTZiZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tDkq-qbW8Fjg8n3pjklHSMZbmITOdNpDR9QTj7QAXds)
> 
> 3- Esto es un detalle, por algún motivo en especial se definió que el "value" por defecto sea "Button"? No sería mejor que no aparezca nada así no tenemos que enviarlo como null?

Mauro te respondo una por una:
1 - La diferencia entre un type main y secondary es:
- la altura en el main es 50 y en el secondary 42.
- cuando es variant outlined: A - en el main es black y en el secondary es el color seleccionado.
- en algunos casos muestra sombra, eso lo habia agregado pero se lo quité porque al revisar el flujo en delivery no tiene por lo que se puede intuir que la sombra se la agregan aparte por estilos.

[LINK](https://www.figma.com/file/ShLWx4A5qDLctovUii3gJW/Mejoras-de-dise%C3%B1o?type=design&node-id=6402-759&mode=design&t=eysm1wMK9pXtkwoL-0)

2 - En éste caso como muestra en el link del diseño de los botones, en main no es que no hace efecto sino que éste es asi...

3 - En realidad, mi idea era que si no tenia value o icon, no se motrara nada pero ahi surgieron dos problemas:
- Un error en los hooks cuando devuelve un null o un <></>.
- En la tabla de props que dejo fer en el ticket, puso que value es requeriada. 

Entonces para solucionar ambos errores, deje por defecto el value="Button", pero teniendo en cuenta que hay botones sin texto deje abierta la posibilidad de pasarle un null para que no se muestre lo cual no se si  esta bien del todo. Vos decime, si queres mandamos null, y comentamos con esling-ignore las lineas donde me salen los errores en hooks.

2024-04-17 20:14 UTC, Maukr approved these changes

2024-04-18 19:03 UTC, christian97dd requested changes
Dejé unos comentarios, pero por el momento dejamos un poco pausada esta tarea para poder darle foco al flujo de movimientos de productos de wms.
Mientras tanto usemos el button que tenemos en cada app y para el flujo nuevo le agregamos los bordes redondeados

2024-04-18 22:16 UTC, dam788 commented on src/components/Button/index.tsx
> +	const [isPressed, setIsPressed] = useState<Boolean>(false);
la idea original era esa misma, pero se complicó cuando quise extender los estilos de BaseButton a Button. Ahi dejó de funcionar y tuve que buscar una alternativa

2024-04-18 22:17 UTC, dam788 commented on src/components/Button/index.tsx
> +		<Loading isLoading={isLoading} color={buttonStyle.loadingColor} size={24} />
Es verdad, crei que tenia que tomar el color seleccionado. Buen punto

2024-06-03 22:32 UTC, WilliamSaya-lvl30 approved these changes
Lo veo bien

2024-06-04 20:09 UTC, GonzaFran approved these changes

2024-06-06 13:20 UTC, christian97dd requested changes
Lo ví mucho mejor, lo único que me hace ruido es cuando se le pasa el isLoading en true, a penas se vé:
![image](https://github.com/janis-commerce/ui-native/assets/49655553/c29fbd2a-38fa-4ce8-9810-fb741ccf9a3e)

Convendría deshabilitarlo y que quede siempre el loading con el color de janis:
![image](https://github.com/janis-commerce/ui-native/assets/49655553/3fb1df0f-6a34-4a96-aee9-d4578e3cf077)

2024-06-06 17:08 UTC, merged