Crear componente Toast
janis-commerce/ui-native pull request #37
Opened 2024-06-10 15:47 UTC by dam788

### LINK DE TICKET:

https://janiscommerce.atlassian.net/browse/APPSRN-308

### DESCRIPCIÓN DEL REQUERIMIENTO:

**Contexto:**

En las tres apps estamos usando notificaciones para mostrar distintos mensajes y tenemos bastante codigo duplicado como tambien distintas maneras de usarlo. Por ejemplo en picking tenemos varios tipos de toast que se podrían mejorar y simplificar. 

Con todo el desarrollo de push notification, las notificaciones cada vez van a ser mas importantes y por tal motivo necesitamos tener dicha funcionalidad de una manera mas agnóstica, reutilizable y que permite escalar el codigo de una manera mas rápida para agilizar entregas

**Necesidad:**

Tener los distintos tipos de notificaciones desde la [libreria](https://github.com/janis-commerce/ui-native)  con sus distintos tipos

Como funciona hoy en las **apps?**

Desde la [libreria](https://www.npmjs.com/package/react-native-toast-message) estamos usando en App.js el componente Toast, el cual se encarga de recibir la configuracion de todos los Toast posibles.

La configuracion implica declarar el tipo de toast (este tipo es importante porque luego se usa para mostrar los distintos Toast en base al tipo) y cada uno de ellos esta usando un componente BaseToast.

### DESCRIPCIÓN DE LA SOLUCIÓN:
- se instalo "react-native-toast-message": ">=1.6.0" y se agregó como peerDependency.
- Se creó un componente BaseToast, del cual parte el componente Toast, que es el componente básico.
- Se crearon las configuraciones de toast llamadas configToast y se exportaron por el index de ui-native y tambien se exporto Toast de "react-native-toast-message", para consumirse directamente desde ui-native.

### CÓMO SE PUEDE PROBAR?

**En storybook:**

- `npm i`
- `npm start` && `npm run storybook:web`}

**En alguna de las apps:**

- En el repo de ui-native correr en consola: `yalc publish`
- En la app: `yalc add @janis-commerce/ui-native`
- En App.js reemplazar el componente Toast que se usa como provider:

```
import {Toast as ToastProvider, configToast} from '@janiscommerce/ui-native';
		
//donde configAppToast es la configuracion de los toast locales
<ToastProvider
     config={{...configAppToast, ...configToast}}
     ref={(ref) => ToastProvider.setRef(ref)}
     {...defaultConfig}
/>

```
- Llamar donde quiera a `Toast.show({title1: 'prueba de toast'})`, por ejemplo en **Home.js**

### SCREENSHOTS:

![Kapture 2024-06-10 at 12 37 00](https://github.com/janis-commerce/ui-native/assets/60529414/a988bbe3-fbf9-40b1-813d-28dedaee6ff1)

### CHANGELOG:

2024-06-12 18:56 UTC, pablonortiz approved these changes
Lo estuve probando y lo vi bien

2024-06-12 22:38 UTC, WilliamSaya-lvl30 requested changes

2024-06-12 22:38 UTC, WilliamSaya-lvl30 commented on src/components/BaseButton/index.tsx
> +	style?: any;
El type correcto no es any si no ViewStyle.
`style?: ViewStyle;`

2024-06-12 22:42 UTC, WilliamSaya-lvl30 commented
Adicional a esto el componente no esta adaptado a las nuevas caracteristicas que implimenta diseño en los toast.
![Captura de pantalla de 2024-06-12 19-34-36](https://github.com/janis-commerce/ui-native/assets/69169114/ea280030-0f7f-421f-aa8d-6b8cc52a9df6)

Lo comentare en el canal para confirmar que se va a realizar esto en esta historia.

2024-06-18 13:03 UTC, pablonortiz approved these changes

2024-06-18 13:51 UTC, GonzaFran requested changes
@dam788  se dejaron comentarios y consultas en el PR

2024-06-18 13:51 UTC, GonzaFran commented on src/components/Toast/index.tsx
> +	if (!validType) {
@dam788 unificá estos `if`, total retornan lo mismo

2024-06-18 13:51 UTC, GonzaFran commented on src/components/Toast/index.tsx
> +interface Props extends ToastProps {
@dam788 todas las propiedades que agregan más funcionalidad al `toast` están dentro de una key `props` por algo en particular?

2024-06-18 14:50 UTC, dam788 commented on src/components/BaseButton/index.tsx
> +	style?: any;
este no pertenece a este ticket

2024-06-18 14:51 UTC, dam788 commented on src/components/Toast/index.tsx
> +interface Props extends ToastProps {
Ahi le cambie el nombre

2024-06-18 15:54 UTC, GonzaFran approved these changes

2024-06-18 16:37 UTC, WilliamSaya-lvl30 approved these changes

2024-06-27 00:00 UTC, pablodamianberdun requested changes
Mejorar nombres de props del componente Toast

2024-06-27 22:35 UTC, pablodamianberdun approved these changes

2024-06-27 22:35 UTC, merged