Checkbox component
janis-commerce/ui-native pull request #4
Opened 2023-03-03 22:38 UTC by dam788

**LINK DE TICKET:**
https://janiscommerce.atlassian.net/browse/JUIP-75

**DESCRIPCIÓN DEL REQUERIMIENTO:**

**Contexto**
No contamos en la librería de apps con el componente checkbox y la consecuencia de esto es que tengamos un componente en cada apps, repitiendo codigo , con la posibilidad de que se generen distintos bugs y que sea dificil de mantener y escalar

**Necesidad**
contar con un componente reutilizable que podamos usar en las distintas apps de Janis teniendo un codigo único para facilitar la escalabilidad y soporte.

[Figma](https://www.figma.com/file/ZWLyF29DMLh5ywkBnuHVZi/Janis-Delivery-App---DEV?node-id=0%3A154&t=nPsqdItRCU5bkmhp-0)

**DESCRIPCIÓN DE LA SOLUCIÓN:**

Se creo el componente Image en src/components y se agrego su correspondiente archivo de stories en la carpeta storybook

Debe poseer las siguientes props:
Prop | Valor default | Requerido | Tipo | Observaciones
-- | -- | -- | -- | --
value |   | true | bool | obligatorio
onValueChange | ()=>{} | false | func | callback utilizado para actualizar el state de value
customSize | 18px | false | number | si viene toma el valor de la prop  customSize y no el default.
disabled | false | false | bool | si viene toma el valor de la prop  disabled y no el default.
checkOnColor | #2979FF | false | string | color sólido cuando el checkbox esta en on.
checkOffColor | #939598 | false | string | color del borde cuando el checkbox esta en off.
iconCheckColor | #FFF | false | string | color del icono del check.

</div></div>

**CÓMO SE PUEDE PROBAR?**
Clonar e instalar el Repo de UI-Native

Correr los siguientes 3 comandos en tres pestañas diferentes de la termina

npm run start
npm run android
npm run storybook

Se debe abrir la app en el emulador con storybooks y el navegador en la url http://localhost:7007/ donde se podrá probar
el comportamiento del componente

Para linkear el componente con un proyecto, seguir la siguiente documentación
https://fizzmod.atlassian.net/wiki/spaces/JAPP/pages/2341765125/C+mo+trabajo+con+el+package+UI

2023-03-07 16:36 UTC, pablonortiz requested changes
Acá cambiaria el nombre de la prop value, porque cuando usas el componente y queres ponerlo en true lo podes poner cómo:
`<CheckBox value />`
Y estaría apareciendo el check, lo que no lo hace muy intuitivo, por eso lo cambiaría a algo cómo checked o active cosa de que se pueda usar así:
`<CheckBox active />`

2023-03-08 12:16 UTC, pablonortiz approved these changes

2023-03-08 16:27 UTC, GonzaFran requested changes
@dam788 Te dejo 2 comentarios de unos ajustes que me gustaría que vieras y me dijeras si son viables o si, en todo caso, no valen la pena por alguna razón

2023-03-08 16:27 UTC, GonzaFran commented on src/components/CheckBox/index.tsx
> +			borderRadius: getCheckBoxScale(customSize),
@dam788 agregaría una prop "borderRadius" especifica  para el borderRadius, porque, al usar el customSize como parámetro, estas atando el redondeo del checkbox al tamaño customizado y nunca podrías lograr, en caso de quererlo, un redondeo total, o un checkbox sin redondeo en sus bordes, lo ves viable?

2023-03-08 16:27 UTC, GonzaFran commented on src/components/CheckBox/index.tsx
> +			<View style={isChecked} {...props}>
@dam788 creo que convendría cambiar el lugar donde estás aplicando las props, pasandolo de View a TouchableOpacity  (que en este caso es el componente padre) para que, si aplico propiedades de estilo, no sobrescriban las del componente View

2023-03-09 19:08 UTC, dam788 commented on src/components/CheckBox/index.tsx
> +			<View style={isChecked} {...props}>
corregido

2023-03-09 19:08 UTC, dam788 commented on src/components/CheckBox/index.tsx
> +			borderRadius: getCheckBoxScale(customSize),
corregido

2023-03-09 23:04 UTC, GonzaFran approved these changes

2023-03-13 20:02 UTC, Maukr approved these changes

2023-03-17 12:44 UTC, colomfernando commented
@dam788 tengo algunas consultas/sugerencias. 
- Revisando el figma https://www.figma.com/file/caDK6jFUsHJ0V1GdGw38Jy/%E2%9D%96-Libreria-de-Janis-Apps?node-id=0-4487&t=8WRkk7kdbeOOOROx-0 el icono check es mas chico.
- Por otro lado, veo que pasamos unos colores por default, estaria bueno tener esos colores en alguna carpeta llamada theme y su archivo colors porque se van a reutilizar en varios lados.
- La interface deberia tener un export tambien para que vaya al archivo types que se genera
- El icon lo veo bien por ahora pero despues vamos a tener que hacer un componente icon aparte.
- La funcion onValueChange tiene que tener acceso al valor de checked

2023-03-17 12:45 UTC, colomfernando requested changes
@dam788 tengo algunas consultas/sugerencias.

- Revisando el figma https://www.figma.com/file/caDK6jFUsHJ0V1GdGw38Jy/%E2%9D%96-Libreria-de-Janis-Apps?node-id=0-4487&t=8WRkk7kdbeOOOROx-0 el icono check es mas chico.
- Por otro lado, veo que pasamos unos colores por default, estaria bueno tener esos colores en alguna carpeta llamada theme y su archivo colors porque se van a reutilizar en varios lados.
- La interface deberia tener un export tambien para que vaya al archivo types que se genera
- El icon lo veo bien por ahora pero despues vamos a tener que hacer un componente icon aparte.
- La funcion onValueChange tiene que tener acceso al valor de checked
- Para la proxima, tener en cuenta el nombre de la branch, de ponerle el issue de jira

2023-03-22 21:37 UTC, closed without merging