Fixed buttons positions for LayoutWithBottomButtons
janis-commerce/ui-native pull request #43
Opened 2024-09-26 14:59 UTC by pablonortiz

LINK DE TICKET:
https://janiscommerce.atlassian.net/browse/JUIP-155

DESCRIPCIÓN DEL REQUERIMIENTO:
A partir del uso de los componentes LayoutWithBottomButtons y Button se encontraron errores en estos componentes, por el lado de LayoutWithBottomButtons no se están renderizando los botones y Button cuenta con un tipografía erronea.

DESCRIPCIÓN DE LA SOLUCIÓN:
Se corrigieron los errores en ambos componentes, añadiendo además las nuevas disposiciones necesarias para el LayoutWithBottomButtons según diseño.

CÓMO SE PUEDE PROBAR?
Vinculando el package con algún repo de las apps: https://janiscommerce.atlassian.net/wiki/spaces/JAPP/pages/2341765125/C+mo+trabajo+con+el+package+UI

Y probando que todas las distintas disposiciones del componente LayoutWithBottomButtons se vean correctamente

Para poder probarlo de una manera más sencilla se pueden utilizar los siguientes códigos para pasarle a la prop buttons del componentes:

**Botón de icono y botón con texto redondeados**
`const buttons = [
  {
  icon: 'camera',
  color: 'black',
  onPress: () => {},
  },
  {
  color: getColor('primary', 'main'),
  value: 'Continuar',
  onPress: () => {},
  },
]
`

**Dos botones de texto redondeados (uno siempre es más largo que el otro)**
`const buttons = [
  {
  color: getColor('primary', 'main'),
  value: 'Continuar',
  onPress: () => {},
  },
  {
  color: 'getColor('base', 'white')',
value: 'Posponer',
variant: 'outlined',
	textStyle: {
			color: getColor('primary', 'main'),
		},
  onPress: () => {},
  },
]
`
**Un botón sobre otro (pasarle al componente LayoutWithBottomButtons la variant "roundedOnTop"**
`const buttons = [
  {
  color: getColor('primary', 'main'),
  value: 'Continuar',
  onPress: () => {},
  },
  {
  color: 'getColor('base', 'white')',
value: 'Añadir Persona',
variant: 'outlined',
	textStyle: {
			color: getColor('primary', 'main'),
		},
  onPress: () => {},
  },
]
`
![Screenshot_20240925_155119_ui-native](https://github.com/user-attachments/assets/955ea50c-8f53-4eec-8aa2-f51f45bad8dc)
![Screenshot_20240925_155304_ui-native](https://github.com/user-attachments/assets/c607703e-796d-4416-9a87-d94f7a7541ae)
![Screenshot_20240925_155345_ui-native](https://github.com/user-attachments/assets/d43e27cd-9ee0-4751-a3ff-69e34f66f3a8)

DATOS EXTRA A TENER EN CUENTA:
CHANGELOG:

2024-10-09 14:33 UTC, GonzaFran requested changes
@pablonortiz deje unas consultas en el PR, del resto lo vi bien

2024-10-09 14:33 UTC, GonzaFran commented on src/components/molecules/LayoutWithBottomButtons/utils/index.ts
> +
@pablonortiz esta validación no es inncesaria? si dentro de la condición la variable siempre arranca en `false`,para qué hacemos la validación de la linea 127? no conviene directamente asignarle el valor que resulte de la inea 128? o es por algo más que se hizo así?

2024-10-09 14:33 UTC, GonzaFran commented on src/components/molecules/Button/index.tsx
@pablonortiz en caso de que no se recibe ni un icono ni un valor, no deberíamos retornar un `null` ? de lo contrario se muestra un botón con un background nada más

2024-10-10 15:05 UTC, pablonortiz commented on src/components/molecules/LayoutWithBottomButtons/utils/index.ts
> +
@GonzaFran nono, esto lo había hecho así porque cuándo hay un botón que sólo tiene icono y otro botón con texto es distinto el espacio que ocupan, pasaría esto:

Con esas lineas de código:
![Screenshot_20241010_115021_ui-native](https://github.com/user-attachments/assets/351d62c5-bfe0-4f72-a17f-23dc6fac46be)

Sin esas lineas:
![Screenshot_20241010_115029_ui-native](https://github.com/user-attachments/assets/680c9bbc-c902-4c92-b787-48b48c1e8ca9)

2024-10-10 15:06 UTC, pablonortiz commented on src/components/molecules/Button/index.tsx
Si, muy buena observación, ahí ya lo corregí!

2024-10-14 16:20 UTC, GonzaFran requested changes
@pablonortiz dejo un comentario para fixear el estilo del icono

2024-10-14 16:20 UTC, GonzaFran commented on src/components/molecules/Button/utils/getButtonStyles/utils/styleConfigs/index.ts
> +		lineHeight: scaledForDevice(19, moderateScale),
@pablonortiz estuve viendolo en el emulador y, por la escala de lineheight, el icono me aparece cortado. Aunque sólo probé en 2 emuladores de diferente tamaño.

Así se vió en ambos con 19 como valor para lineHeight:
![Captura desde 2024-10-14 13-05-01](https://github.com/user-attachments/assets/53577083-c54d-417f-bd77-1bb3c98d8724)

Así sacando la propiedad:
![Captura desde 2024-10-14 13-05-24](https://github.com/user-attachments/assets/47d3f1e1-3b7b-48fc-89c2-e1a8113763ad)

Y así, aumentando el valor para la prop a 25:
![Captura desde 2024-10-14 13-18-24](https://github.com/user-attachments/assets/a8c50339-8c96-4f93-890c-ba59d5c0e92f)

Te diría que revises qué es más conveniente, el resto ya lo veo para aprobar, quedó este detalle nada más

2024-10-14 17:42 UTC, pablonortiz commented on src/components/molecules/Button/utils/getButtonStyles/utils/styleConfigs/index.ts
> +		lineHeight: scaledForDevice(19, moderateScale),
Corregido!

2024-10-14 17:45 UTC, GonzaFran approved these changes

2024-10-14 18:46 UTC, merged