Appsrn 340 implementación del componente typography
janis-commerce/ui-native pull request #45
Opened 2024-10-10 17:02 UTC by pablonortiz

LINK DE TICKET:
https://janiscommerce.atlassian.net/browse/APPSRN-340

DESCRIPCIÓN DEL REQUERIMIENTO:
Actualmente contamos con un componente Text que se encarga de renderizar el texto y nos permite modificar sus estilos para adaptarlo a nuestras necesidades, recientemente, desde diseño, se [establecieron ciertas tipografías](https://www.figma.com/design/FLybyH52rc4EapUG1qjMPc/Design-System?node-id=5441-16450&node-type=frame&t=8zyJDEs6SCPFMPwL-0) que serán las que van a estar siendo usadas a lo largo de todas las apps, desde el lado de diseño también van a estar estableciendo el tipo y tamaño de esta tipografía a partir de la guía, por lo que, esto nos abre la posibilidad para implementar directamente en un componente la implementación de estas tipografías de manera tal que sean más faciles de usar, para no tener que estar haciendo uso de las tipografías manualmente.

DESCRIPCIÓN DE LA SOLUCIÓN:
Se añadió el componente Typography, el cuál, a partir de las props de type y size que se le pasen renderiza el texto con los estilos que cumplen el diseño establecido en la guía de figma

CÓMO SE PUEDE PROBAR?
Vinculando el package con algún repo de las apps: https://janiscommerce.atlassian.net/wiki/spaces/JAPP/pages/2341765125/C+mo+trabajo+con+el+package+UI

Y probando que las distintas tipografías de los textos funcionen correctamente.

2024-12-04 18:08 UTC, christian97dd requested changes
se deja un comentario

2024-12-04 18:08 UTC, christian97dd commented on src/components/atoms/RadioButton/index.test.tsx
> +import Text from 'atoms/Typography';
es una boludes, pero para mantener un standard, tratemos de no renombrar los componentes cuando los importamos, en este caso seria un import Typography, no queda mal el nombre :p, lo mismo con los demas

2024-12-04 18:42 UTC, pablonortiz commented on src/components/atoms/RadioButton/index.test.tsx
> +import Text from 'atoms/Typography';
Corregido!

2024-12-05 14:33 UTC, christian97dd approved these changes

2024-12-05 14:35 UTC, merged