added baseCollapsible component
janis-commerce/ui-native pull request #48
Opened 2024-12-03 16:33 UTC by GonzaFran

LINK DE TICKET:
https://janiscommerce.atlassian.net/browse/JPRN-1995

CONTEXTO:

En el desarrollo que vamos a trabajar en la app de orders (https://janiscommerce.atlassian.net/browse/ATR-1427) necesitamos usar colapsables para rediseñar los canastos que pertenecen a cada pedido de una ronda, y, ya que en todos los repos de apps se utiliza el componente `Collapsible` como esqueleto para trabajar cada colapsable dentro de la aplicación, se decidió que sería más práctico tener el componente dentro de ui-native para facilitar su utilización en cada caso.

NECESIDAD:

Agregar el componente `Collapsible` en ui-native

SOLUCIÓN: 

https://www.npmjs.com/package/react-native-collapsible

Se agregó la dependencia `react-native-collapsible` al repo para poder utilizar el componente `Accordion` y desarrollar el componente `BaseCollapsible`.
Este componente hereda las propiedades del componente `Accordion` y permite contar con un recurso básico para adaptarlo a cada situación en la que se requiera usar el colapsable.
Para poder utilizarlo correctamente es necesario:
- Agregar una función `renderHeader` que retorne un elemento de react que representa el header del colapsable al estar plegado y desplegado.
- Agregar una función `renderContent` que retorne un elemento react que representará el contenido del colapsable cuando esté desplegado.
- Agregar un array con información para la prop `Sections`, que contendrá toda la data que deberá renderizar cada colapsable. (Tener en cuenta que, para poder ver esta info, es necesario que `renderHeader` y `renderContent` la utilicen como argumentos)

¿CÓMO PROBARLO? 
Puede vincular el pkg al repo que quiera e importar el componente BaseCollapsible para reemplazar cualquiera de los collapsbiles que esté usando actualmente en la aplicación.

En caso de tener un problema similar a este al tratar de levantar la aplicación
```js
Error: Command failed: ./gradlew app:installBetaDebug -PreactNativeDevServerPort=8081
error Unable to resolve module atoms/SwipeUp/childComponents from /var/www/janis-picking-app/.yalc/@janiscommerce/ui-native/dist/index.js: atoms/SwipeUp/childComponents could not be found within the project or in these directories:
  node_modules
  11 | import Svg from 'atoms/Svg';
  12 | import SwipeUp from 'atoms/SwipeUp';
> 13 | import { SwipeUpFlatList, SwipeUpScrollView, SwipeUpView } from 'atoms/SwipeUp/childComponents';
     |                                                                  ^
  14 | import Text from 'atoms/Text';
  15 | import BaseInput from 'atoms/BaseInput';
  16 | import BaseCollapsible from 'atoms/BaseCollapsible';

FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':app:createBundleBetaDebugJsAndAssets'.
> Process 'command 'node'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
```

Lo que debe hacer, dentro del pkg de ui-native, es correr el comando `npm run build`

También puede ver el funcionamiento desde storybooks.

2024-12-04 18:36 UTC, pablonortiz approved these changes
Lo estuve probando en la app de Delivery, storybook y storybook web y lo vi bien!

2025-01-08 15:47 UTC, pablonortiz requested changes
Lo estuve probando y lo vi joya, lo único que estaría faltando es pullearte master y resolver unos conflictos, con eso ya estaría!

2025-02-04 14:25 UTC, christian97dd requested changes
según lo conversado se necesita:
- que el componente Collapsible reciba una prop llamada `renderAsFlatlist`
- en caso de que venga la prop, el content deberá ser renderizado dentro de una flatlist que te permita el scrollear
- si la prop no viene o viene en false, el content se renderiza dentro de un View

2025-02-05 16:28 UTC, pablonortiz commented
@christian97dd ya se realizaron los ajustes del componente, se ignoraron ciertas lineas en los tests porque no se pudieron testear y se hicieron las pruebas con 3000 elementos:
https://gifyu.com/image/b2lpl

2025-02-05 20:39 UTC, christian97dd approved these changes

2025-02-05 20:41 UTC, merged