Added Input component
janis-commerce/ui-native pull request #6
Opened 2023-05-31 20:31 UTC by pablonortiz

**LINK DE TICKET:**
https://janiscommerce.atlassian.net/browse/JUIP-83

**DESCRIPCIÓN DEL REQUERIMIENTO:**

Actualmente no contamos con un componente Input reutilizable, por lo que nos obliga en todas las apps a tener código repetido, y en caso de querer hacer alguna modificación, se deberá cambiar en las 3 apps por igual.

Por esto mismo, se necesita tener el componente input reutilizable disponible en el package UI para facilitar su escalabilidad.

**DESCRIPCIÓN DE LA SOLUCIÓN:**

Se creó el componente Input en src/component/Input, agregándose los utils, tests y storybooks correspondientes.

Además, se agregó una interface de palette conteniendo todos los distintos colores del theme dentro de src/theme/palette.ts, esto para poder ser utilizada por los utils.

**CÓMO SE PUEDE PROBAR?**
Clonar e instalar el Repo de UI-Native

Correr los siguientes 3 comandos en tres pestañas diferentes de la termina

npm run start
npm run android
npm run storybook

Se debe abrir la app en el emulador con storybooks y el navegador en la url http://localhost:7007/ donde se podrá probar
el comportamiento del componente

Para linkear el componente con un proyecto, seguir la siguiente documentación
https://fizzmod.atlassian.net/wiki/spaces/JAPP/pages/2341765125/C+mo+trabajo+con+el+package+UI

**SCREENSHOTS:**
![Screenshot_1685564620](https://github.com/janis-commerce/ui-native/assets/100979152/31c63936-d9ba-4e1f-8e7c-bc5290730bb3)

![Screenshot_1685564593](https://github.com/janis-commerce/ui-native/assets/100979152/25d9c9dd-ba11-4ca4-908a-230b54f57bb1)

2023-06-02 17:45 UTC, dam788 reviewed
Me hace mucho ruido el readOnly. Decime si estoy equivocado, es parecido a disabled pero con la salvedad que no le pasas las props que son obligatorias como label y placeholder.

2023-06-02 19:42 UTC, dam788 approved these changes

2023-06-05 13:26 UTC, GonzaFran approved these changes

2023-06-08 17:30 UTC, colomfernando commented
@pablonortiz pulleate master asi resolves conflictos con el componente Text que agregaste

2023-06-08 18:43 UTC, pablonortiz commented
@colomfernando listo, ahí ya resolví los conflictos

2023-06-09 21:16 UTC, Maukr approved these changes

2023-06-16 13:08 UTC, colomfernando requested changes
En base a lo que hablamos @pablonortiz se elimaria los extends de las interface para dejar una sola que es InputProps. Tanto label como placeholder se hace requerido dado que no tiene sentido hacer un input readOnly sin valores

Ademas eliminar del interface la key props con any y tambien corregir del enum emailAdress que seria EmailAddress

2023-06-16 13:18 UTC, pablonortiz commented
@colomfernando ahí ya hice los cambios!

2023-07-17 20:23 UTC, GonzaFran requested changes
@pablonortiz según lo que hablamos, sólo faltaría agregar la configuración para poder editar las props de storybook desde la web

2023-07-26 14:21 UTC, GonzaFran approved these changes

2023-07-26 21:45 UTC, dam788 approved these changes

2023-08-08 13:30 UTC, merged